// Generated by LiveScript 1.6.0
export default (async function(){
  var a;
  a = '../w3ui.js';
  a = (await fetch(a).then(async function(r){
    return r.text();
  })['catch'](function(){
    return null;
  }));
  if (!a) {
    return null;
  }
  a = a.substring(a.indexOf('function'));
  a = new Function('"use strict";return ' + a);
  return a();
}());
/***/