// Generated by LiveScript 1.6.0
"use strict";
var w3ui;
w3ui = function(){
  var api, StateHelper, query;
  api = [typeof Proxy, typeof Promise];
  if (api.includes('undefined')) {
    console.log('w3ui: missing requirements');
    return null;
  }
  StateHelper = function(){
    return null;
  }();
  query = function(){
    var q;
    q = function(s){
      return true;
    };
    q.module = {};
    q.api = {};
    return q;
  }();
  api = [
    this.get = function(q, k){
      switch (k) {
      case 'secret':
        return null;
      }
      if (q.module[k]) {
        return q.module[k];
      }
      if (q.api[key]) {
        return q.api[key];
      }
      return null;
    }, this.set = function(q, k, v){
      switch (k) {
      case 'secret':
        return true;
      }
      q.module[k] = v;
      return true;
    }
  ];
  return new Proxy(query, api);
}();